# Configuration yaml
# =============================================================================
# Created By  : Ben Grodner
# Created Date: 2022_01_28
# =============================================================================
# This is an example configuration file for the split probe design pipeline. Adjust
    # as necessary for your needs.
# These values get loaded into the snakemake as a dictionary in the variable 'config'
# =============================================================================

## Paths
input_dir: data # Relative path to wherever your input images are from the
                  # projecet workdir
output_dir: segmentation # relative path of the directory you want to write to,
                        # does not need to exist yet
pipeline_path: pipeline_segmentation # relative path to the pipeline folder from workdir
functions_path: functions  # Path to function scripts relative to the pipeline path

## Inputs
input_ext: .czi  # Extenstion for image files
input_table_fn: input_table.csv  # path to table of input images
input_table_cols: [sample_name]  # Add to if you want different params for
                                  # different images, one colum must be "sample_name"
conda_env: hiprfish_imaging_py38
snakefile: Snakefile  # name of the snakefile in the pipeline path
# conda_env_fn: ../envs/hiprfish_imaging_py38.yaml  # environment filename relative
#                                                 # to the rules folder in the pipeline

## Params
cell_seg:
  fn_mod: _cell_seg
  channels: [0]
  pre_log: False  # Pre-processing: take the log? used for high signal variance
  pre_denoise: True  # Use denoise non-local means?
  pre_gauss: 2.5  # Gaussian filter? no if zero, otherwise value sets the sigma
  bg_filter: True  # Do we even want to subtract the background?
  bg_log: True  # Take the log of the image in auto background subtraction
  bg_smoothing: 0  # Pixels for gaussian blurring in auto background subtraction
  n_clust_bg: 3  # Number of clusters to use in auto background subtraction
  top_n_clust_bg: 2  # how many clusters to use as foreground in auto background subtraction
  bg_threshold: 0  # Manual value of background subtraction threshold
                  # overrides auto background subtraction
  n_clust: 2  # Number of clusters to use in LNE foreground selection
  small_objects: 50  # Remove segmented objects with pixel area smaller than this value
  maxima: False  # Locate maxima in segmentaiton and get intensities there

spot_seg:
  fn_mod: _spot_seg
  channels: [1]
  pre_log: False  # Pre-processing the segmentation image: take the log
  pre_denoise: True  # Use denoise non-local means?
  pre_gauss: 0  # Gaussian filter? no if zero, otherwise value sets the sigma
  bg_filter: False  # Do we even want to subtract the background?
  bg_log: False  # Take the log of the image in auto background subtraction
  bg_smoothing: 0  # Pixels for gaussian blurring in auto background subtraction
  n_clust_bg: 2  # Number of clusters to use in auto background subtraction
  top_n_clust_bg: 1  # how many clusters to use as foreground in auto background subtraction
  bg_threshold: 0.005  # Manual value of background subtraction threshold
                  # overrides auto background subtraction
  n_clust: 2  # Number of clusters to use in LNE foreground selection
  small_objects: 50  # Remove segmented objects with pixel area smaller than this value
  maxima: True  # Locate maxima in segmentaiton and get intensities there

seg_process_dpi: 500
seg_process_ext: _process.pdf
local_max_mindist: 3
max_dist_to_cell: 5
